
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/board?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: boarduser
    password: a1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: coderun91@gmail.com
    password: cwoyqmbaneedaykv
    properties:
      mail:
        smtp:
          starttls:
            enable: true

logging:
  level:
    org.hibernate.SQL: debug


mybatis:
  mapper-locations: mybatis/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl